services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: jacobmaynard
      POSTGRES_PASSWORD: dumbInfinity42$
      POSTGRES_DB: studiobookingdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
